services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 bot:flask_app
    envVars:
      - key: BOT_TOKEN
        sync: false # Set manually in Render dashboard
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
