services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker bot:flask_app
    envVars:
      - key: BOT_TOKEN
        sync: false # Set this manually in Render dashboard
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
