services:
  - type: worker
    name: pdf-renamer-bot
    runtime: python
    repo: https://github.com/Jaggibhau/telegram-pdf-rename-bot
    branch: main
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
